<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ndi_format" type="ndi_format_type"/>
    <xs:complexType name="ndi_format_type">
        <xs:sequence>
            <xs:element name="video_format" minOccurs="0">
                <xs:complexType>
                    <xs:attribute name="xres" type="xs:int" use="required" />
                    <xs:attribute name="yres" type="xs:int" use="required" />
                    <xs:attribute name="frame_rate_n" type="xs:int" use="required" />
                    <xs:attribute name="frame_rate_d" type="xs:int" use="required" />
                    <xs:attribute name="aspect_ratio" type="xs:decimal" use="required" />
                    <xs:attribute name="progressive" type="xs:boolean" use="required" />
                </xs:complexType>
            </xs:element>
            <xs:element name="audio_format" minOccurs="0">
                <xs:complexType>
                    <xs:attribute name="no_channels" type="xs:int" use="required" />
                    <xs:attribute name="sample_rate" type="xs:int" use="required" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
