<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
    xmlns:xsi="http://www.w3.org/2007/XMLSchema-instance"
    vc:minVersion="1.1">

    <!-- Connection Metadata -->
    <xs:include schemaLocation="ndi_product.xsd"/>
    <xs:include schemaLocation="ndi_capabilities.xsd"/>

    <!-- Generic Metadata -->
    <xs:include schemaLocation="ndi_metadata_element.xsd"/>
    <xs:include schemaLocation="ntk_ptz.xsd"/>
    <xs:include schemaLocation="ndi_kvm.xsd"/>

    <xs:element name="ndi_metadata_group">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="ndi_metadata" type="ndi_metadata_type">
                    <xs:alternative test="@type = 'midi'" type="metadata-midi_type"/>
                    <xs:alternative test="@type = 'dmx'" type="metadata-dmx_type"/>
                </xs:element>
                <xs:element name="SALRAY_DMX" type="legacy-dmx_type"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>
